#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
register_page:
    path: /register
    controller: App\Controller\RegisterController::show
